name: sync-strings-action
description: Sync Android strings between two folders (from src to dest).
inputs:
  toml_path:
    description: Path to project config file (TOML), relative to the folder's root
    required: true
  src:
    description: Source folder
    required: true
  dest:
    description: Destination folder
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.toml_path }}
    - ${{ inputs.src }}
    - ${{ inputs.dest }}
